# Generated by Django 5.2.5 on 2025-09-07 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='uploads/%y/%m/%d'),
        ),
    ]
